### ISSUE TITLE
shopping list retrieve

### ISSUE THREAD

**Issue by FreeFlight-Code** [theRealFoodFinder/food-finder#90]
TypeError: Cannot read property 'get_shopping_list' of undefined
    at app.get (C:\Users\COMP\Desktop\food-finder\server\server.js:636:18)
    at Layer.handle [as handle_request] (C:\Users\COMP\Desktop\food-finder\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\COMP\Desktop\food-finder\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\COMP\Desktop\food-finder\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\COMP\Desktop\food-finder\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\COMP\Desktop\food-finder\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\COMP\Desktop\food-finder\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\COMP\Desktop\food-finder\node_modules\express\lib\router\index.js:275:10)
    at SessionStrategy.strategy.pass (C:\Users\COMP\Desktop\food-finder\node_modules\passport\lib\middleware\authenticate.js:338:9)
    at SessionStrategy.authenticate (C:\Users\COMP\Desktop\food-finder\node_modules\passport\lib\strategies\session.js:75:10)

**Comment by FreeFlight-Code** [comment]
fixed
